name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests before deployment'
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Run Tests
    if: github.event.inputs.skip_tests != 'true'
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      always() && 
      (needs.test.result == 'success' || github.event.inputs.skip_tests == 'true')
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /var/www/aso_store
          
          # Сохраняем текущую версию на случай отката
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit: $CURRENT_COMMIT"
          
          # Обновляем код
          git fetch origin main
          git reset --hard origin/main
          
          # Запускаем скрипт обновления
          if bash deploy/update.sh; then
            echo "✅ Deployment successful!"
            
            # Проверяем здоровье приложения
            sleep 10
            if bash deploy/health-check.sh; then
              echo "✅ Health check passed!"
            else
              echo "❌ Health check failed! Rolling back..."
              git reset --hard $CURRENT_COMMIT
              bash deploy/update.sh
              exit 1
            fi
          else
            echo "❌ Deployment failed!"
            exit 1
          fi
        EOF

    - name: Send notification
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: |
          Deployment ${{ job.status }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          Message: ${{ github.event.head_commit.message }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      continue-on-error: true