name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ labeled ]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/develop' || 
      contains(github.event.pull_request.labels.*.name, 'deploy-staging')
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker images
      run: |
        echo "Building staging images..."
        # Здесь можно добавить сборку Docker образов для staging
        # docker build -t aso-backend:staging ./backend
        # docker build -t aso-frontend:staging ./frontend

    - name: Deploy to staging
      env:
        STAGING_HOST: ${{ secrets.STAGING_HOST }}
        STAGING_USER: ${{ secrets.STAGING_USER }}
      run: |
        echo "Deploying to staging environment..."
        # Здесь добавить команды для развертывания на staging

    - name: Run E2E tests on staging
      run: |
        echo "Running E2E tests against staging..."
        # npm run test:e2e:staging

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 Deployed to staging! Preview: https://staging.aso-store.com'
          })